In [1]:
import numpy as np

In [2]:
data = np.arange(1,13).reshape(3,4)
print("Original Tensor :\n",data)

Original Tensor :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
splits = np.split(data,2,axis=1)
print("\n Split Parts:")
for part in splits:
    print(part)


 Split Parts:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [5]:
merged = np.concatenate(splits,axis=1)
print("\n Merged Tensor :\n",merged)


 Merged Tensor :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
mean_val = np.mean(data)
max_val = np.max(data)
min_val = np.min(data)
sum_val = 

In [8]:
import tensorflow as tf

In [9]:
data = tf.constant([[1,2,3,4],[5,6,7,8],[0,10,11,12]],dtype = tf.float32)
print("Original Tensor :\n",data.numpy())

Original Tensor :
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 0. 10. 11. 12.]]


In [10]:
splits = tf.split(data,num_or_size_splits=2,axis=1)

In [11]:
print("\n Split Parts:")
for part in splits:
    print(part.numpy())


 Split Parts:
[[ 1.  2.]
 [ 5.  6.]
 [ 0. 10.]]
[[ 3.  4.]
 [ 7.  8.]
 [11. 12.]]


In [14]:
print("\n Split Parts:")
for part in splits:
    print(part.numpy())


 Split Parts:
[[ 1.  2.]
 [ 5.  6.]
 [ 0. 10.]]
[[ 3.  4.]
 [ 7.  8.]
 [11. 12.]]


In [18]:
mean_val = tf.reduce_mean(data)
max_val = tf.reduce_max(data)
min_val = tf.reduce_min(data)
sum_val = tf.reduce_sum(data)
std_val = tf.math.reduce_std(data)

In [21]:
print("\nStatistics:")
print(f"Mean: {mean_val.numpy()}")
print(f"Max: {max_val.numpy()}")
print(f"Min: {min_val.numpy()}")
print(f"Sum: {sum_val.numpy()}")
print(f"Standard Deviation: {std_val.numpy()}")



Statistics:
Mean: 5.75
Max: 12.0
Min: 0.0
Sum: 69.0
Standard Deviation: 3.788689374923706
