In [3]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [4]:
print("Tensor A:\n", A)
print("Tensor B:\n", B)

Tensor A:
 [[1 2]
 [3 4]]
Tensor B:
 [[5 6]
 [7 8]]


In [5]:
add=A+B
sub=A-B
mul=A*B
div=A/B
matmul=A@B
print(add,"1\n" , sub, "2\n", mul,"3\n" ,div, "4\n", matmul)

[[ 6  8]
 [10 12]] 1
 [[-4 -4]
 [-4 -4]] 2
 [[ 5 12]
 [21 32]] 3
 [[0.2        0.33333333]
 [0.42857143 0.5       ]] 4
 [[19 22]
 [43 50]]


In [6]:
import tensorflow as tf

In [7]:
A=tf.constant([[1,2],[3,4]])
B=tf.constant([[5,6],[7,8]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [9]:
add=tf.add(A,B)
sub=tf.subtract(A,B)
mul=tf.multiply(A,B)
div=tf.divide(A,B)
matmul=tf.matmul(A,B)

In [10]:
add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [11]:
sub

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [12]:
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [13]:
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

In [14]:
matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [15]:
#SECOND PROGRAM 

In [16]:
#Create a 3x4 tensor
data=np.arange(1,13).reshape(3,4)
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
#Split into 2 parts along columns (axis=1)
splits=np.split(data,2, axis=1)
for part in splits:
    print(part)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [18]:
#Merge back into original tensor
merged=np.concatenate(splits, axis=1)
print("\nMerged Tensor:", merged)


Merged Tensor: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
#STATISTICS
mean_val=np.mean(data)
max_val=np.max(data)
min_val=np.min(data)
sum_val=np.sum(data)
std_val=np.std(data)

In [23]:
print("\nStatistics:")
print(f"Mean:{mean_val}")
print(f"Max:{max_val}")
print(f"Min:{min_val}")
print(f"Sum:{sum_val}")
print(f"Std:{std_val}")


Statistics:
Mean:6.5
Max:12
Min:1
Sum:78
Std:3.452052529534663
